### ISSUE TITLE
Invalid Makefile.m4

### ISSUE THREAD

**Issue by monacofj** [courselab/soii21-jmambrini#1]
When you run `make pack` it should not copy `Makefile.m4`, otherwise build will fail complaining about missing `docm4.m4`.
Just removing `Makefile.m4` fixes the problem.

**Comment by Jmambrini** [comment]
O arquivo docm4.m4 estava sendo direcionado de maneira errada no Makefile.m4. Corrigi os caminhos e isso também corrigiu o problema.
