### ISSUE TITLE
Does it just boot and halt?

### ISSUE THREAD

**Issue by monacofj** [courselab/soii21-jmambrini#2]
When #1 is fixed, the program runs.
Apparently, it just starts and halt... this is it?

**Comment by Jmambrini** [comment]
Utilizei um patch do git, e por algum motivo, ele não aplicou com o git patch. Fiz as mudanças manualmente, corrigi bugs pontuais, e aparentemente está tudo ok.
Porém, devido àqueles problemas de hardware que comentei, não consegui testar em uma máquina.
